# Generated by Django 3.1.3 on 2020-11-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_auto_20201111_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
    ]
