# Generated by Django 3.1.3 on 2020-11-21 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_ad_advertiser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='click',
            old_name='time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='time',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='create_time',
        ),
        migrations.AddField(
            model_name='ad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='click',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='view',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
