# Generated by Django 3.1.3 on 2020-11-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_auto_20201111_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='views',
        ),
    ]
