# Generated by Django 3.1.3 on 2020-11-11 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0005_click_review_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='click_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ad',
        ),
        migrations.AddField(
            model_name='click',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='advertising.ad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='view',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='advertising.ad'),
            preserve_default=False,
        ),
    ]
