# Generated by Django 3.1.3 on 2020-11-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0006_auto_20201111_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
