# Generated by Django 3.1.3 on 2020-11-12 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0007_ad_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='view_delay',
            field=models.DurationField(default=datetime.timedelta(seconds=2400)),
            preserve_default=False,
        ),
    ]
