# Generated by Django 3.1.3 on 2020-11-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='name',
        ),
    ]
